apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - env:
        - name: MONGODB_DBNAME
          valueFrom:
            configMapKeyRef:
              key: MONGODB_DBNAME
              name: mongo-docker-env-mongo-development-env
        - name: MONGODB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MONGODB_PASSWORD
              name: mongo-docker-env-mongo-development-env
        - name: MONGODB_ROLE
          valueFrom:
            configMapKeyRef:
              key: MONGODB_ROLE
              name: mongo-docker-env-mongo-development-env
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MONGODB_ROOT_PASSWORD
              name: mongo-docker-env-mongo-development-env
        - name: MONGODB_ROOT_ROLE
          valueFrom:
            configMapKeyRef:
              key: MONGODB_ROOT_ROLE
              name: mongo-docker-env-mongo-development-env
        - name: MONGODB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              key: MONGODB_ROOT_USERNAME
              name: mongo-docker-env-mongo-development-env
        - name: MONGODB_USERNAME
          valueFrom:
            configMapKeyRef:
              key: MONGODB_USERNAME
              name: mongo-docker-env-mongo-development-env
        image: danwahlin/mongo
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
