version: '3.1'

services:
    viz:
        image: dockersamples/visualizer
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - "9080:8080"
        deploy:
            placement:
                constraints:
                    - node.role==manager
